name: EC2 Deploy via SSH

on:
  push:
    branches:
      - main # main 브랜치로 푸시될 때 워크플로우 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # SSH 키 설정
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # EC2에 SSH로 접속하여 su 명령으로 사용자 전환 후 코드 배포
      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "${{ secrets.SFACE_PASSWORD }}" | su - sface -c "
            cd ~/vite-react-test &&
            git pull origin main &&
            npm ci &&
            npm run build
          "'
